### ISSUE TITLE
As faculty I want to be able to create a syllabus using data I have about my course.

### ISSUE THREAD

**Issue by LightningGuard** [LightningGuard/Syllabus-Creation-Tool#4]
Prompt staff to input relevant information about their course and generate a generic syllabus based on the data they input.

This will require some sort of interface such as a survey-like page on the site.

**Comment by Jamesf15182** [comment]
"# Syllabus-Creation-Tool"

For this iteration my main part was to make something that a faculty member could enter data into and create a generic syllabus template based off the data they entered. So, everything I added to the skeleton was clickable button for the faculty and a survey page for them. So, the clickable button was added to the instructor page which it says make a syllabus which will redirect them to the create syllabus page. Once on this page it will be a survey-like page where it ask for data that is needed to create a template once you hit submit. Also, if the data they entered is invalid is will just redirect the page back and produce an error message in the terminal. Finally, if the user hit submit and the data was all valid it will take them to the syllabus viewer page to see the data in a syllabus format.


Software needed to run:
	
For this to function you will need some ide to run the project (I used pycharm). Then for it work you will need python, django, selenium and the driver for the browser you use ( I used chromedriver). The browser driver needs to be place into the templatetags folder inside of core folder of the project for it to work.


How to run the software:

1)First you will need to clone the project 
2)switch to the dev branch
3)Download the .env from Discord and save it to the project root directory (where you git cloned)
4)Download your browser driver and then save it into the project templatetags folder inside of core folder
5)python -m pip install selenium
4)If not using pycharm, create a venv and switch to it
5)python -m pip install -r requirements.txt 
6)python manage.py migrate
7)python manage.py runserver 
8)python manage.py test 


Optional:
if you do not have selenium you can use this in the terminal to install it 

1) python -m pip install selenium


Then to test if the part i did works:

So, you will need to enter this into the terminal and it will do three things. It will first prompt you to the instructor page and then click the make a syllabus button and take you to the next screen. Next, it will input valid data and show what happens if you do so which will reload the screen and give an error in the terminal what was wrong. The next test will prompt the syllabus maker screen and input correct data. Then it will click submit and show the data in a syllabus template.
